## Facilitators

### Dr. [Angel Lareo](mailto:angel.lareo@uam.es)
Assistant Professor at Universidad Autónoma de Madrid. PhD in computational neuroscience. His work focuses on neural network modeling and he interdisciplinary applications of free technologies, exploring the potential of free/libre open source software and hardware in areas of social interest such as sustainability and neuroscience. In sustainability, he has developed low-power monitoring devices—such as the Arduino-based BtM datalogger—as well as a computational model of GHG emissions in eco-social transition scenarios. In the field of neuroscience, he began his research career working on closed-loop experimental studies, which led to his interest in the modeling and simulation of complex dynamic systems, developing and managing the Neun neural model library.

### Dr. [Alicia Garrido-Peña](mailto:alicia.garrido@uam.es)
Assistant Professor at Universidad Autónoma de Madrid. PhD in computational neuroscience. Her work focuses on Computational Neuroscience, trying to unveil neural dynamics from a hybrid and multidisciplinary approach: through electrophysiology experiments, computational models, and closed-loop real-time activity-dependent stimulation. As an early career researcher she is currently exploring other research paths in the field, such as the modeling of complex networks for cognitive neuroscience and the neurological problems caused by the addictive use of smartphones. Her other interests include, computer science, FLOSS and open and inclusive science. (https://agarpe.github.io/)
